# Generated by Django 4.2.6 on 2024-05-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movie_casting_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_casting',
            name='movie',
        ),
    ]
