# Generated by Django 4.2.6 on 2024-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_movie_details_cast_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_details',
            name='cast_members',
        ),
        migrations.AddField(
            model_name='movie_details',
            name='cast_memberz',
            field=models.ManyToManyField(related_name='movies', to='base.movie_casting'),
        ),
    ]
