# Generated by Django 4.2.6 on 2024-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_cast_memberz_movie_details_cast_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='full_story',
            field=models.CharField(default='full story', max_length=1000, null=True),
        ),
    ]
